# Generated by Django 4.2.16 on 2026-05-05 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_types', '0002_add_slug_y_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_utc', models.DateTimeField()),
                ('fin_utc', models.DateTimeField()),
                ('nombre_invitado', models.CharField(max_length=150)),
                ('email_invitado', models.EmailField(max_length=254)),
                ('notas', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('confirmacion_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='event_types.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'reservas',
                'ordering': ['-inicio_utc'],
                'indexes': [models.Index(fields=['host', 'estado', 'inicio_utc'], name='ix_reserva_host_estado_inicio')],
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'confirmada')), fields=('host', 'inicio_utc'), name='uq_reserva_host_inicio_confirmada'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('fin_utc__gt', models.F('inicio_utc'))), name='ck_reserva_fin_mayor_inicio'),
        ),
    ]
