# Generated by Django 4.2.16 on 2026-05-12 13:36

from django.db import migrations, models


def backfill_estado_error(apps, schema_editor):
    Reserva = apps.get_model('bookings', 'Reserva')
    Reserva.objects.filter(google_sync_estado='pendiente').update(google_sync_estado='error')


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reserva',
            name='google_meet_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reserva',
            name='google_sync_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.RunPython(backfill_estado_error, reverse_backfill),
    ]
