# Generated by Django 4.2.16 on 2026-06-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_plantillas_estado_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcorreo',
            name='html_content',
            field=models.TextField(blank=True, default='', verbose_name='Contenido HTML'),
        ),
        migrations.AddField(
            model_name='logcorreo',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='configcorreodefault',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configcorreoevento',
            name='plantilla_confirmacion_host',
            field=models.ForeignKey(blank=True, help_text='Si no se selecciona, Google Calendar solo notifica al host si el invitado confirma manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_confirmacion_host', to='bookings.plantillacorreo', verbose_name='Correo al host'),
        ),
        migrations.AlterField(
            model_name='configcorreogrupo',
            name='plantilla_confirmacion_host',
            field=models.ForeignKey(blank=True, help_text='Se aplica a todos los miembros del grupo salvo que el evento tenga su propia config. Sin plantilla, Google Calendar solo notifica al host si el invitado confirma manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_grupo_confirmacion_host', to='bookings.plantillacorreo', verbose_name='Correo al host'),
        ),
    ]
