# Generated by Django 4.2.16 on 2026-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_logcorreo_html_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcorreo',
            name='tipo',
            field=models.CharField(choices=[('confirmacion_host', 'Confirmación host'), ('confirmacion_inv', 'Confirmación invitado'), ('recordatorio_1', 'Recordatorio 1'), ('recordatorio_2', 'Recordatorio 2'), ('cancelacion', 'Cancelación')], max_length=30),
        ),
    ]
