# Generated by Django 4.2.16 on 2026-06-05 19:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('bookings', '0019_fix_logcorreo_tipo_confirmacion_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
