# Generated by Django 4.2.16 on 2026-06-08 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0003_grupo_bloqueos_v2'),
        ('bookings', '0020_reserva_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCorreoMiembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_correo_miembro', to='grupos.grupo')),
                ('plantilla_confirmacion_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.plantillacorreo', verbose_name='Correo al host')),
                ('plantilla_confirmacion_inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.plantillacorreo', verbose_name='Correo al invitado')),
                ('plantilla_recordatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.plantillacorreo', verbose_name='Plantilla de recordatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_correo_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de correo por miembro',
                'verbose_name_plural': 'Configuraciones de correo por miembro',
                'db_table': 'config_correo_miembro_grupo',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
