# Generated by Django 4.2.16 on 2026-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_reserva_event_id_reserva_journey_id_reserva_utm_adid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='uq_reserva_host_inicio_confirmada',
        ),
        migrations.AddField(
            model_name='reserva',
            name='permite_overbooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'confirmada'), ('permite_overbooking', False)), fields=('host', 'inicio_utc'), name='uq_reserva_host_inicio_confirmada'),
        ),
    ]
