# Generated by Django 4.2.16 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_remove_reserva_uq_reserva_host_inicio_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='url',
            field=models.CharField(blank=True, default='', help_text='window.location.href del visitante al momento de reservar.', max_length=1500, verbose_name='URL de origen'),
        ),
    ]
