# Generated by Django 4.2.16 on 2026-08-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_reserva_setter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DominioRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Etiqueta para reconocerlo en el admin. Ej. Conquer Blocks.', max_length=100, verbose_name='Nombre')),
                ('dominio', models.CharField(help_text='Dominio verificado en Mailgun. Ej. conquerblocks.com', max_length=255, unique=True, verbose_name='Dominio')),
                ('region', models.CharField(choices=[('eu', 'Europa (api.eu.mailgun.net)'), ('us', 'Estados Unidos (api.mailgun.net)')], default='eu', help_text='La región en la que está dado de alta el dominio. Si no coincide, el envío falla.', max_length=2, verbose_name='Región de Mailgun')),
                ('from_email', models.CharField(help_text='Dirección desde la que sale el correo. Ej. Conquer Blocks <noreply@conquerblocks.com>', max_length=255, verbose_name='Remitente (From)')),
                ('reply_to', models.EmailField(blank=True, default='', help_text='Buzón real al que llegan las respuestas del destinatario. Déjalo vacío solo si nadie va a leer las respuestas.', max_length=254, verbose_name='Responder a (Reply-To)')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, las plantillas que lo usen vuelven al remitente por defecto de la app.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Dominio de envío',
                'verbose_name_plural': 'Dominios de envío',
                'db_table': 'dominios_remitente',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='formato',
            field=models.CharField(choices=[('html', 'HTML (con logo, colores y botones)'), ('texto', 'Texto plano (sin HTML)')], default='html', help_text='En texto plano se envía solo el cuerpo, sin logo, colores ni botones.', max_length=10, verbose_name='Formato del correo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_1_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_2_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantillacorreo',
            name='cuerpo',
            field=models.TextField(help_text='Variables: {{nombre_invitado}}, {{email_invitado}}, {{nombre_host}}, {{nombre_evento}}, {{fecha_hora}}, {{duracion}}, {{google_meet_url}}, {{link_cancelar}}, {{link_reagendar}}, {{link_confirmar}}'),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='dominio',
            field=models.ForeignKey(blank=True, help_text='Desde qué dominio sale este correo. Vacío = remitente por defecto de la app (el de siempre).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='bookings.dominioremitente', verbose_name='Dominio de envío'),
        ),
    ]
