# Generated by Django 4.2.16 on 2026-08-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0028_dominios_remitente_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('panel', 'Panel interno'), ('publica', 'El invitado, desde su enlace'), ('sync_gcal', 'Rechazo del host en Google Calendar'), ('comando', 'Comando de mantenimiento'), ('reagendada', 'Reagendada (se movió a otra hora)'), ('desconocido', 'Sin identificar')], default='desconocido', max_length=20)),
                ('detalle', models.CharField(blank=True, default='', help_text='Email del host que rechazó, del invitado que canceló, etc.', max_length=255)),
                ('correo_enviado', models.BooleanField(default=False, help_text='Si se avisó al invitado por Google al cancelar.')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones', to='bookings.reserva')),
                ('usuario', models.ForeignKey(blank=True, help_text='Quién la canceló, cuando se sabe (panel o comando).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cancelación de reserva',
                'verbose_name_plural': 'cancelaciones de reservas',
                'db_table': 'cancelaciones_reserva',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['-creada_en'], name='ix_cancelacion_fecha'), models.Index(fields=['origen'], name='ix_cancelacion_origen')],
            },
        ),
    ]
