# Generated by Django 4.2.16 on 2026-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_reserva_alumno_lms_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email concreto'), ('dominio', 'Dominio entero')], default='email', max_length=10)),
                ('valor', models.CharField(help_text='Email concreto: <code>pepito@gmail.com</code> (el resto de gmail sigue pudiendo reservar).<br>Dominio: <code>somoshackers.com</code> bloquea ese dominio y sus subdominios; sin extensión, <code>somoshackers</code> bloquea cualquier terminación (.com, .net, .es…). La arroba del principio da igual.', max_length=254)),
                ('motivo', models.CharField(blank=True, default='', help_text='Nota interna: por qué se bloqueó. No lo ve el invitado.', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para dejar de bloquear sin perder el registro.')),
                ('intentos', models.PositiveIntegerField(default=0, help_text='Reservas que ha frenado este bloqueo.')),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bloqueo de invitado',
                'verbose_name_plural': 'bloqueos de invitados',
                'db_table': 'bloqueos_invitado',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfigBloqueos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_redireccion', models.URLField(blank=True, default='', help_text='A dónde se manda a quien intenta reservar estando bloqueado. Vacío: a la página propia «Lo sentimos, tu reserva no pudo ser procesada».', max_length=500, verbose_name='URL de redirección')),
            ],
            options={
                'verbose_name': 'Configuración de bloqueos',
                'verbose_name_plural': 'Configuración de bloqueos',
                'db_table': 'config_bloqueos',
            },
        ),
        migrations.AddConstraint(
            model_name='bloqueoinvitado',
            constraint=models.UniqueConstraint(fields=('tipo', 'valor'), name='uq_bloqueo_tipo_valor'),
        ),
    ]
