# Generated by Django 4.2.16 on 2026-05-07 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_types', '0002_add_slug_y_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeXHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_pool', to='event_types.eventtype')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types_round_robin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'host de round-robin',
                'verbose_name_plural': 'hosts de round-robin',
                'db_table': 'event_types_x_hosts',
                'ordering': ['event_type_id', 'id'],
                'indexes': [models.Index(fields=['event_type'], name='ix_etxh_event_type'), models.Index(fields=['host'], name='ix_etxh_host')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtypexhost',
            constraint=models.UniqueConstraint(fields=('event_type', 'host'), name='uq_etxh_event_type_host'),
        ),
    ]
