# Generated by Django 4.2.16 on 2026-05-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0004_backfill_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug_equipo',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
