# Generated by Django 4.2.16 on 2026-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0009_aviso_minimo_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='aviso_minimo_minutos',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin aviso mínimo'), (15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (120, '2 horas'), (180, '3 horas'), (1440, '1 día'), (4320, '3 días'), (14400, '10 días')], default=0),
        ),
    ]
