# Generated by Django 4.2.16 on 2026-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0010_alter_eventtype_aviso_minimo_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='incremento_inicio_minutos',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos'), (60, '60 minutos')], help_text='Cada cuántos minutos aparece un slot. Si está vacío, usa la duración.', null=True),
        ),
    ]
