# Generated by Django 4.2.16 on 2026-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0011_add_incremento_inicio_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='incremento_inicio_minutos',
            field=models.PositiveSmallIntegerField(choices=[(15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos'), (60, '60 minutos')], default=30, help_text='Cada cuántos minutos aparece un slot disponible.'),
        ),
    ]
