# Generated by Django 4.2.16 on 2026-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0021_seed_confirmacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='gcal_palabras_ignorar',
            field=models.TextField(blank=True, default='', help_text='Reglas free/busy: si un evento de Google Calendar contiene alguna de estas palabras o emojis en su título, NO bloqueará los horarios (se podrá agendar encima). Una por línea. Si se le quita la palabra al evento en Google Calendar, vuelve a bloquear. Solo aplica a hosts con sincronización de calendario activa.', verbose_name='Palabras/emojis que liberan el horario'),
        ),
    ]
