# Generated by Django 4.2.16 on 2026-07-28 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0022_eventtype_gcal_palabras_ignorar'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='max_reservas_por_slot',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cuántas reservas activas admite un mismo horario mientras las reglas de arriba lo mantienen abierto. Al llegar al tope el horario se cierra solo, sin tener que tocar Google Calendar. Solo cuentan las confirmadas: si una se cancela vuelve a quedar sitio para otra. Con el valor 1 no se admite ninguna reserva encima.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Máximo de reservas por horario'),
        ),
    ]
