# Generated by Django 4.2.16 on 2026-07-28 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0023_eventtype_max_reservas_por_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='max_reservas_por_slot',
        ),
        migrations.AddField(
            model_name='eventtypexhost',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=1, help_text='De 1 a 3, donde 3 es la más alta. Cuando varios organizadores están libres a la misma hora, la reserva se asigna al de mayor prioridad; a igualdad de prioridad decide el reparto de carga de siempre.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Prioridad en el round-robin'),
        ),
    ]
