# Generated by Django 4.2.16 on 2026-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0026_prioridad_cero_excluye'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='rango_fecha_fin',
            field=models.DateField(blank=True, help_text='Solo se usa con el rango de fechas concreto. Es un día inclusive.', null=True, verbose_name='Reservable hasta'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='rango_fecha_inicio',
            field=models.DateField(blank=True, help_text='Solo se usa con el rango de fechas concreto.', null=True, verbose_name='Reservable desde'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='rango_tipo',
            field=models.CharField(choices=[('rolling', 'Días rodantes (a partir de hoy)'), ('fechas', 'Rango de fechas concreto')], default='rolling', max_length=10, verbose_name='Tipo de rango de reserva'),
        ),
    ]
