# Generated by Django 4.2.16 on 2026-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0027_rango_fechas_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='mostrar_caja_comentarios',
            field=models.BooleanField(default=True, help_text="Muestra el campo 'Notas (opcional)' en el formulario de reserva, tanto en la página pública como en los funnels.", verbose_name='Caja de comentarios'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='gcal_palabras_ignorar',
            field=models.TextField(blank=True, default='', help_text='Reglas free/busy: si un evento de Google Calendar contiene alguna de estas palabras o emojis en su título, NO bloqueará los horarios (se podrá agendar encima). Una por línea. Si se le quita la palabra al evento en Google Calendar, vuelve a bloquear. Solo aplica a hosts con sincronización de calendario activa. Para que las reservas de ESTE tipo de evento se puedan pisar entre sí, pon la palabra en el nombre del tipo de evento (la app nunca la añade sola al título).', verbose_name='Palabras/emojis que liberan el horario'),
        ),
    ]
