# Generated by Django 4.2.16 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0030_slug_equipo_finance_latam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='unico_por_invitado',
            field=models.BooleanField(default=True, help_text='Si está activo, un mismo email (o un mismo teléfono) no puede reservar este evento dos veces mientras tenga una reserva futura confirmada.'),
        ),
    ]
