# Generated by Django 4.2.16 on 2026-08-14 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0031_alter_eventtype_unico_por_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='aviso_maximo_dias',
            field=models.PositiveSmallIntegerField(default=60, help_text='Rango máximo (rolling) en días naturales desde hoy. El último día entra entero: con 3 días, el día de hoy+3 se abre completo a sus 00:00, no hora a hora conforme avanza el reloj.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
