# Generated by Django 4.2.16 on 2026-08-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0032_alter_eventtype_aviso_maximo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='acceso',
            field=models.CharField(choices=[('publico', 'Público — cualquiera con el enlace'), ('academia', 'Solo alumnos — requiere acceso desde la academia')], default='publico', help_text='«Solo alumnos» restringe la reserva a quien entre desde la academia. La página deja de ser accesible por su enlace directo.', max_length=20, verbose_name='Quién puede reservar'),
        ),
    ]
