# Generated by Django 4.2.16 on 2026-08-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_horario_bloquehorariofecha_horario_and_more'),
        ('event_types', '0033_eventtype_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtypexhost',
            name='horario',
            field=models.ForeignKey(blank=True, help_text='Sin nada seleccionado usa el horario por defecto del organizador. Al asignar uno concreto, ese sustituye al de por defecto solo para este tipo de evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types_x_hosts', to='availability.horario', verbose_name='Horario que usa en este evento'),
        ),
    ]
