# Generated by Django 4.2.16 on 2026-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0036_borrar_disponibilidad_etxh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='acceso',
            field=models.CharField(choices=[('publico', 'Público — cualquiera con el enlace'), ('transicion', 'Público, y además embebible en la academia'), ('academia', 'Solo alumnos — requiere acceso desde la academia')], default='publico', help_text='«Solo alumnos» restringe la reserva a quien entre desde la academia: la página deja de ser accesible por su enlace directo. La opción intermedia permite el embebido sin cerrar todavía el enlace, para poder hacer el cambio en dos pasos.', max_length=20, verbose_name='Quién puede reservar'),
        ),
    ]
