# Generated by Django 4.2.16 on 2026-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0039_academia_lms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='academia_lms_id',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Conquer Blocks'), (2, 'Conquer Finance'), (3, 'Conquer Languages')], help_text='A qué academia pertenecen estas sesiones. Vacío = la sesión se registra igual, pero no entra en los recuentos por academia.', null=True, verbose_name='Academia en el LMS'),
        ),
    ]
