# Generated by Django 4.2.16 on 2026-09-15 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0040_alter_eventtype_academia_lms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='limite_reservas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas reservas puede tener un mismo invitado cada «días del límite». Vacío: sin límite.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de reservas por invitado'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='limite_reservas_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tamaño de la ventana, contada por la fecha de la cita. Con 1 reserva cada 30 días, quien tuvo cita el 10/09 no puede tener otra hasta el 10/10.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días del límite'),
        ),
    ]
