# Generated by Django 4.2.16 on 2026-06-05 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_types', '0009_aviso_minimo_minutos'),
        ('bookings', '0019_fix_logcorreo_tipo_confirmacion_inv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Réplica del `key` de formObj. Ej. FullLatam.', max_length=50, unique=True, verbose_name='Clave')),
                ('slug', models.SlugField(help_text='Identificador para la URL /f/<slug>/.', max_length=80, unique=True, verbose_name='Slug')),
                ('escuela', models.CharField(help_text='Ej. conquer-blocks, conquer-finance, conquer-languages, conquer-legal.', max_length=40, verbose_name='Escuela')),
                ('region', models.CharField(help_text='latam / eu / us.', max_length=10, verbose_name='Región')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('config', models.JSONField(blank=True, default=dict, help_text='blocks, q_order, validate, neverCancel, score_ranges, cancel_screen, settings, theme, messages.', verbose_name='Configuración (JSON)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'formulario de funnel',
                'verbose_name_plural': 'formularios de funnel',
                'db_table': 'funnel_forms',
                'ordering': ['escuela', 'region'],
            },
        ),
        migrations.CreateModel(
            name='FunnelScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=list, help_text='Array de scores (réplica de scores.jsx).', verbose_name='Tabla de puntuaciones (JSON)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tabla de puntuaciones',
                'verbose_name_plural': 'tabla de puntuaciones',
                'db_table': 'funnel_scoring',
            },
        ),
        migrations.CreateModel(
            name='Prellamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('respuestas', models.JSONField(blank=True, default=dict, help_text='dict {campo: valor} de todas las respuestas.', verbose_name='Respuestas')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resultado', models.CharField(choices=[('calendario', 'Calendario'), ('rechazado', 'Rechazado')], max_length=20)),
                ('tracking', models.JSONField(blank=True, default=dict, help_text='UTM/journey opcional, sin lógica MVP.', verbose_name='Tracking')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prellamadas', to='event_types.eventtype')),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prellamadas', to='funnels.funnelform')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prellamada', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'prellamada',
                'verbose_name_plural': 'prellamadas',
                'db_table': 'prellamadas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['funnel', 'creado_en'], name='ix_prellamada_funnel_creado'), models.Index(fields=['resultado'], name='ix_prellamada_resultado')],
            },
        ),
    ]
