# Generated by Django 4.2.16 on 2026-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0006_seed_funnel_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelform',
            name='slug',
            field=models.SlugField(help_text='Identificador interno del funnel (usado en la API /f/api/<slug>/).', max_length=80, unique=True, verbose_name='Slug'),
        ),
    ]
