# Generated by Django 4.2.16 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0009_prellamada_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='prellamada',
            name='journey_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='prellamada',
            name='resultado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('calendario', 'Calendario'), ('rechazado', 'Rechazado')], max_length=20),
        ),
    ]
