# Generated by Django 4.2.16 on 2026-09-01 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funnels', '0028_contenido_de_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidodeevento',
            name='borrador',
            field=models.JSONField(blank=True, default=dict, help_text='Cambios sin publicar. Solo se ven en la vista previa.', verbose_name='Borrador'),
        ),
        migrations.AddField(
            model_name='contenidodeevento',
            name='publicado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última publicación'),
        ),
        migrations.AddField(
            model_name='contenidodeevento',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por'),
        ),
        migrations.AlterField(
            model_name='contenidodeevento',
            name='textos',
            field=models.JSONField(blank=True, default=dict, help_text='{clave: valor} de los textos en vivo. Lo que falte sale del código.', verbose_name='Textos publicados'),
        ),
    ]
