# Generated by Django 4.2.16 on 2026-05-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSyncEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_token', models.TextField(blank=True, default='')),
                ('canal_id', models.CharField(blank=True, default='', max_length=200)),
                ('canal_resource_id', models.CharField(blank=True, default='', max_length=200)),
                ('canal_expira_utc', models.DateTimeField(blank=True, null=True)),
                ('ultima_sync_utc', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('sin_sincronizar', 'Sin sincronizar'), ('activo', 'Activo'), ('error', 'Error')], default='sin_sincronizar', max_length=20)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcal_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estado de sync de Google Calendar',
                'verbose_name_plural': 'estados de sync de Google Calendar',
                'db_table': 'google_calendar_sync_estado',
                'indexes': [models.Index(fields=['canal_expira_utc'], name='ix_gcal_sync_expira')],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=1024)),
                ('inicio_utc', models.DateTimeField()),
                ('fin_utc', models.DateTimeField()),
                ('es_todo_el_dia', models.BooleanField(default=False)),
                ('transparencia', models.CharField(default='opaque', max_length=20)),
                ('estado', models.CharField(default='confirmed', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_gcal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de Google Calendar',
                'verbose_name_plural': 'eventos de Google Calendar',
                'db_table': 'google_calendar_eventos',
                'ordering': ['host_id', 'inicio_utc'],
                'indexes': [models.Index(fields=['host', 'inicio_utc', 'fin_utc'], name='ix_gcal_evento_host_rango')],
            },
        ),
        migrations.AddConstraint(
            model_name='googlecalendarevento',
            constraint=models.UniqueConstraint(fields=('host', 'google_event_id'), name='uq_gcal_evento_host_event'),
        ),
        migrations.AddConstraint(
            model_name='googlecalendarevento',
            constraint=models.CheckConstraint(check=models.Q(('fin_utc__gt', models.F('inicio_utc'))), name='ck_gcal_evento_fin_mayor_inicio'),
        ),
    ]
