# Generated by Django 4.2.16 on 2026-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(choices=[('sync_inicial', 'sync_gcal_inicial'), ('sync_incremental', 'sync_gcal_incremental'), ('watch_gcal', 'watch_gcal'), ('renovar_canales', 'renovar_canales_gcal')], max_length=30)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('exitosos', models.PositiveIntegerField(default=0)),
                ('fallidos', models.PositiveIntegerField(default=0)),
                ('hosts_fallidos', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'log de sync',
                'verbose_name_plural': 'logs de sync',
                'db_table': 'google_calendar_sync_log',
                'ordering': ['-ejecutado_en'],
                'indexes': [models.Index(fields=['ejecutado_en'], name='ix_gcal_log_ejecutado'), models.Index(fields=['comando'], name='ix_gcal_log_comando')],
            },
        ),
    ]
