# Generated by Django 4.2.16 on 2026-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0002_log_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevento',
            name='titulo',
            field=models.CharField(blank=True, default='', help_text='Título (summary) del evento en Google Calendar. Se usa para las reglas free/busy por palabra/emoji del tipo de evento.', max_length=1024),
        ),
    ]
