# Generated by Django 4.2.16 on 2026-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEspejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(db_index=True, max_length=20)),
                ('library_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('guid', models.CharField(db_index=True, max_length=36)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('resolucion', models.CharField(blank=True, default='', max_length=10)),
                ('bytes_copiados', models.BigIntegerField(default=0)),
                ('bytes_origen', models.BigIntegerField(default=0)),
                ('r2_key', models.CharField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('copiado', 'Copiado'), ('fallido', 'Fallido'), ('omitido', 'Omitido')], db_index=True, default='pendiente', max_length=12)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('copiado_en', models.DateTimeField(blank=True, null=True)),
                ('borrado_en_bunny', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_backup_espejo',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='videoespejo',
            constraint=models.UniqueConstraint(fields=('library_id', 'guid'), name='uniq_libreria_guid'),
        ),
    ]
