# Generated by Django 4.2.16 on 2026-05-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_disponibilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloque horario semanal',
                'verbose_name_plural': 'bloques horarios semanales',
                'db_table': 'bloques_horarios_semanales',
                'ordering': ['host_id', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='bloquehorariosemanal',
            constraint=models.UniqueConstraint(fields=('host', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_bloque_horario_host_dia_rango'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariosemanal',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_bloque_hora_fin_mayor_inicio'),
        ),
    ]
