# Generated by Django 4.2.16 on 2026-05-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0002_add_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorarioFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_disponibilidad_fecha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloque horario por fecha',
                'verbose_name_plural': 'bloques horarios por fecha',
                'db_table': 'bloques_horarios_fecha',
                'ordering': ['host_id', 'fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['host', 'fecha'], name='ix_bloque_host_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='bloquehorariofecha',
            constraint=models.UniqueConstraint(fields=('host', 'fecha', 'hora_inicio', 'hora_fin'), name='uq_bloque_horario_host_fecha_rango'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariofecha',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_bloque_fecha_hora_fin_mayor_inicio'),
        ),
    ]
