# Generated by Django 4.2.16 on 2026-08-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0003_bloquehorariofecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('es_default', models.BooleanField(default=False, help_text='El que usan los tipos de evento que no tienen uno asignado. Solo puede haber uno por persona y no se puede borrar.', verbose_name='Es el horario por defecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'horarios',
                'ordering': ['host_id', '-es_default', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='bloquehorariofecha',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_fecha', to='availability.horario'),
        ),
        migrations.AddField(
            model_name='bloquehorariosemanal',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_semanales', to='availability.horario'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['host'], name='ix_horario_host'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('host', 'nombre'), name='uq_horario_host_nombre'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(condition=models.Q(('es_default', True)), fields=('host',), name='uq_horario_un_default_por_host'),
        ),
    ]
