# Generated by Django 4.2.16 on 2026-08-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_horario_bloquehorariofecha_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquehorariofecha',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloquehorariofecha',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariofecha',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('hora_fin__isnull', False), ('hora_inicio__isnull', False)), models.Q(('hora_fin__isnull', True), ('hora_inicio__isnull', True)), _connector='OR'), name='ck_bloque_fecha_horas_completas'),
        ),
    ]
