# Generated by Django 4.2.16 on 2026-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_alter_bloquehorariofecha_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorariofecha',
            options={'ordering': ['horario_id', 'fecha', 'hora_inicio'], 'verbose_name': 'bloque horario por fecha', 'verbose_name_plural': 'bloques horarios por fecha'},
        ),
        migrations.AlterModelOptions(
            name='bloquehorariosemanal',
            options={'ordering': ['horario_id', 'dia_semana', 'hora_inicio'], 'verbose_name': 'bloque horario semanal', 'verbose_name_plural': 'bloques horarios semanales'},
        ),
        migrations.RemoveConstraint(
            model_name='bloquehorariofecha',
            name='uq_bloque_horario_host_fecha_rango',
        ),
        migrations.RemoveConstraint(
            model_name='bloquehorariosemanal',
            name='uq_bloque_horario_host_dia_rango',
        ),
        migrations.RemoveIndex(
            model_name='bloquehorariofecha',
            name='ix_bloque_host_fecha',
        ),
        migrations.RemoveIndex(
            model_name='bloquehorariosemanal',
            name='ix_bloque_host_dia',
        ),
        migrations.AddIndex(
            model_name='bloquehorariofecha',
            index=models.Index(fields=['horario', 'fecha'], name='ix_bloque_horario_fecha'),
        ),
        migrations.AddIndex(
            model_name='bloquehorariosemanal',
            index=models.Index(fields=['horario', 'dia_semana'], name='ix_bloque_horario_dia'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariofecha',
            constraint=models.UniqueConstraint(fields=('horario', 'fecha', 'hora_inicio', 'hora_fin'), name='uq_bloque_horario_fecha_rango'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariofecha',
            constraint=models.UniqueConstraint(condition=models.Q(('hora_inicio__isnull', True)), fields=('horario', 'fecha'), name='uq_bloque_horario_fecha_cerrado'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorariosemanal',
            constraint=models.UniqueConstraint(fields=('horario', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_bloque_horario_dia_rango'),
        ),
    ]
