# Generated by Django 4.2.16 on 2026-06-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('bookings', '0020_reserva_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=150)),
                ('task_id', models.CharField(max_length=100)),
                ('exception_type', models.CharField(max_length=200)),
                ('exception_message', models.TextField()),
                ('traceback', models.TextField()),
                ('sentry_event_id', models.CharField(blank=True, default='', max_length=50)),
                ('sentry_url', models.URLField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_failures', to='leads.lead')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_failures', to='bookings.reserva')),
            ],
            options={
                'db_table': 'monitoring_task_failure_log',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_logs', to='leads.lead')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_logs', to='bookings.reserva')),
            ],
            options={
                'db_table': 'monitoring_alert_log',
                'ordering': ['-created'],
            },
        ),
    ]
