# Generated by Django 4.2.16 on 2026-06-05 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('bookings', '0020_reserva_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación.')),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('original_email', models.CharField(blank=True, help_text='Email original antes de corrección automática de sintaxis', max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_phone', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=255, null=True)),
                ('lead_phone_prefix', models.CharField(blank=True, help_text='Prefijo del teléfono del cliente', max_length=255, null=True)),
                ('lead_country', models.CharField(blank=True, help_text='País del cliente', max_length=255, null=True)),
                ('setter_conversation_status', models.CharField(blank=True, choices=[('no_contacted', 'No contactado'), ('not_interested', 'Contactado pero no le interesa'), ('contacted', 'Contactado'), ('scheduled', 'Agendado'), ('pending_schedule', 'Pendiente de llamada')], help_text='Estado de conversación con el Setter', max_length=50, null=True)),
                ('setter_notes', models.TextField(blank=True, help_text='Notas del Setter', null=True)),
                ('is_form_vsl_processed', models.BooleanField(db_index=True, default=False)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_idcampaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_adsetid', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_adid', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_form_variant', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_title', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_vsl', models.CharField(blank=True, max_length=10, null=True)),
                ('gclid', models.CharField(blank=True, max_length=255, null=True)),
                ('gbraid', models.CharField(blank=True, max_length=255, null=True)),
                ('wbraid', models.CharField(blank=True, max_length=255, null=True)),
                ('fbclid', models.CharField(blank=True, max_length=255, null=True)),
                ('msclkid', models.CharField(blank=True, max_length=255, null=True)),
                ('dclid', models.CharField(blank=True, max_length=255, null=True)),
                ('ttclid', models.TextField(blank=True, null=True)),
                ('gclsrc', models.CharField(blank=True, max_length=255, null=True)),
                ('_fbp', models.CharField(blank=True, db_column='_fbp', max_length=255, null=True)),
                ('_fbc', models.CharField(blank=True, db_column='_fbc', max_length=255, null=True)),
                ('_ttp', models.CharField(blank=True, db_column='_ttp', max_length=255, null=True)),
                ('_ga', models.CharField(blank=True, db_column='_ga', max_length=255, null=True)),
                ('_gid', models.CharField(blank=True, db_column='_gid', max_length=255, null=True)),
                ('event_id', models.CharField(blank=True, help_text='Identificador único del evento', max_length=100, null=True)),
                ('journey_id', models.CharField(blank=True, db_index=True, help_text='Identificador de trazabilidad del visitante', max_length=100, null=True)),
                ('recaptcha_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score de reCAPTCHA v3 (0.0 a 1.0)', max_digits=3, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador del cliente', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IPv6 compatible', max_length=45, null=True)),
                ('ipv6_address', models.CharField(blank=True, help_text='Dirección IPv6 del cliente', max_length=45, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('is_proxy', models.CharField(blank=True, max_length=10, null=True)),
                ('page_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('funnel', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('neverbounce_result', models.JSONField(blank=True, help_text='Resultado de validación NeverBounce', null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('meta', 'Meta CAPI'), ('tiktok', 'TikTok Events'), ('google_ads', 'Google Ads')], max_length=20)),
                ('event_name', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pixel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_logs', to='leads.lead')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_logs', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'Conversion Log',
                'verbose_name_plural': 'Conversion Logs',
                'db_table': 'conversion_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['school', 'utm_source', 'date_submitted'], name='leads_school_utm_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='leads_email_upper_idx'),
        ),
    ]
