# Generated by Django 4.2.16 on 2026-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vsl_percent_cb',
            field=models.IntegerField(default=0, help_text='% video Conquer Blocks'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vsl_percent_cf',
            field=models.IntegerField(default=0, help_text='% video Conquer Finance'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vsl_percent_cl',
            field=models.IntegerField(default=0, help_text='% video Conquer Languages'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vsl_percentage',
            field=models.IntegerField(default=0, help_text='% máximo visto del video (genérico)'),
        ),
    ]
